version: '3.8'

services:
  db:
    # We use the official pgvector image which bundles Postgres 15 + the vector extensions natively
    image: pgvector/pgvector:pg15
    container_name: flickfind_postgres
    restart: always
    environment:
      POSTGRES_USER: flickadmin
      POSTGRES_PASSWORD: flicksecretpassword
      POSTGRES_DB: flickfind_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: